adjective = input("Name a noun?")
adjective1 = input("Another adjective, example: good.")
people_animal = input("A person or animal.")
protest_topic = input("What are you protesting?")
possession = input("What is one of your posessions?")
adjective2 = input("Another adjective please")
action = input("Name an action")
adjective3 = input("Another adjective")
noun = input("Name a noun")
animals = input("Name an animal")
place = input("Name a place")


print("There are many people who think that %s is %s, when in reality, it is not." % (adjective,adjective1))
print("These %s sometimes believe strongly enough that they protest against laws trying to stop %s." % (people_animal,protest_topic))
print("Even though we have the %s of %s, the government still does not listen to those protestors and" % (possession,adjective2))
print("continue on with the plan they had. Other than calling the state and asking them whether or not they will %s" % action)
print("%s on a %s, there isn’t much you can do to keep the protestors from getting their way, but with every" % (adjective3,noun))
print("vote against it, more and more %s keep coming from %s." % (animals,place))
